// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// protoc-gen-go-micro version: v3.5.3
// source: grpc.proto

package micro_old_server

import (
	context "context"
	api "go.unistack.org/micro/v3/api"
	client "go.unistack.org/micro/v3/client"
)

var (
	MicroOldServerName = "MicroOldServer"

	MicroOldServerEndpoints = []api.Endpoint{}
)

func NewMicroOldServerEndpoints() []api.Endpoint {
	return MicroOldServerEndpoints
}

type MicroOldServerClient interface {
	Test(ctx context.Context, req *TestRequest, opts ...client.CallOption) (*TestResponse, error)
}

type MicroOldServerServer interface {
	Test(ctx context.Context, req *TestRequest, rsp *TestResponse) error
}
