// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: grpc.proto

package micro_old_server

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for MicroOldServer service

type MicroOldServerService interface {
	Test(ctx context.Context, in *TestRequest, opts ...client.CallOption) (*TestResponse, error)
}

type microOldServerService struct {
	c    client.Client
	name string
}

func NewMicroOldServerService(name string, c client.Client) MicroOldServerService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "micro_old_server"
	}
	return &microOldServerService{
		c:    c,
		name: name,
	}
}

func (c *microOldServerService) Test(ctx context.Context, in *TestRequest, opts ...client.CallOption) (*TestResponse, error) {
	req := c.c.NewRequest(c.name, "MicroOldServer.Test", in)
	out := new(TestResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MicroOldServer service

type MicroOldServerHandler interface {
	Test(context.Context, *TestRequest, *TestResponse) error
}

func RegisterMicroOldServerHandler(s server.Server, hdlr MicroOldServerHandler, opts ...server.HandlerOption) error {
	type microOldServer interface {
		Test(ctx context.Context, in *TestRequest, out *TestResponse) error
	}
	type MicroOldServer struct {
		microOldServer
	}
	h := &microOldServerHandler{hdlr}
	return s.Handle(s.NewHandler(&MicroOldServer{h}, opts...))
}

type microOldServerHandler struct {
	MicroOldServerHandler
}

func (h *microOldServerHandler) Test(ctx context.Context, in *TestRequest, out *TestResponse) error {
	return h.MicroOldServerHandler.Test(ctx, in, out)
}
